// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Dingo, Editor, Mode, Service, bind;
  Editor = require("./editor");
  Mode = require("./module/mode");
  Service = require("./service/service");
  window.service = Service;
  bind = function(el, eve, fn, priority) {
    var _isIE;
    _isIE = window.addEventListener != null ? false : true;
    return el[_isIE ? "attachEvent" : "addEventListener"]("" + (_isIE ? "on" : "") + eve, fn, priority || false);
  };
  Dingo = {};
  Dingo.init = function() {
    var flag, init_interval;
    flag = false;
    return init_interval = setInterval(function() {
      var style;
      console.log("init_interval");
      if (window._dingo_element == null) {
        return;
      }
      clearInterval(init_interval);
      Dingo.element = window._dingo_element;
      if (Dingo.element.css != null) {
        style = document.createElement("style");
        style.textContent = Dingo.element.css;
        document.head.appendChild(style);
      }
      return new Editor($("#editor"), Dingo.element, Service);
    }, 100);
  };
  return module.exports = Dingo;
});
