// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Dingo, Editor, Mode, Service, bind;
  Editor = require("./editor");
  Mode = require("./module/mode");
  Service = {};
  window.service = Service;
  bind = function(el, eve, fn, priority) {
    var _isIE;
    _isIE = window.addEventListener != null ? false : true;
    return el[_isIE ? "attachEvent" : "addEventListener"]("" + (_isIE ? "on" : "") + eve, fn, priority || false);
  };
  Dingo = {};
  Dingo.init = function() {
    return bind(window, "message", function(e) {
      Dingo.element = JSON.parse(e.data);
      console.log("From postMessage", Dingo.element);
      return new Editor($("#editor"), Dingo.element);
    });
  };
  return module.exports = Dingo;
});
