// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var CodeMirror, Editor, beautify;
  CodeMirror = require("codemirror/lib/codemirror");
  beautify = require("../module/beautify/index");
  Editor = (function() {
    function Editor(container, attrs) {
      this.container = container;
      this.attrs = attrs;
      this.container = $(this.container);
      this.ifr_init();
      this.editor_init();
      this.event_bind();
    }

    Editor.prototype.mode = {
      js: "javascript",
      javascript: "javascript",
      html: "htmlmixed",
      css: "css",
      velocity: "velocity"
    };

    Editor.prototype.ifr_init = function() {
      this.ifr = document.createElement("iframe");
      this.ifr.id = "ifr_coder";
      this.ifr.scrolling = "no";
      this.ifr.setAttribute("class", "renderer coder");
      this.ifr.setAttribute("scrolling", "yes");
      this.container.find("#renderer-container").append(this.ifr);
    };

    Editor.prototype.ifr_refresh = function() {
      var doc, script, style;
      try {
        doc = this.html_editor.doc.getValue().trim();
        if (doc === "") {
          doc = "<div></div>";
        }
        this.ifr.contentWindow.document.close();
        this.ifr.contentWindow.document.write(doc);
        style = document.createElement("style");
        script = document.createElement("script");
        style.textContent = this.css_editor.doc.getValue();
        script.text = this.js_editor.doc.getValue();
        this.ifr.contentWindow.document.head.appendChild(style);
        this.ifr.contentWindow.document.body.appendChild(script);
      } catch (_error) {}
    };

    Editor.prototype.editor_init = function() {
      var querycheck, self;
      self = this;
      this.flag = 0;
      window.codeList = $("<div>" + this.attrs.innerHTML + "</div>");
      codeList.find("textarea").each(function() {
        var code_type;
        self.flag++;
        code_type = $(this).attr("code");
        return require(["codemirror/mode/" + self.mode[code_type] + "/" + self.mode[code_type]], (function(_this) {
          return function() {
            var code_content, codemirrorinit, menu;
            self.flag--;
            menu = $("<div class='mode-tab ' codetype='code" + code_type + "'>" + code_type + "<div class='arrow-up '></div></div>");
            self.container.find("#mode-tabs").append(menu);
            codemirrorinit = document.createElement("textarea");
            codemirrorinit.id = "code" + code_type;
            self.container.find("#code-editor").append(codemirrorinit);
            self[code_type + "_editor"] = CodeMirror.fromTextArea(self.container.find("#" + codemirrorinit.id)[0], {
              theme: "monokai",
              lineNumbers: true,
              matchBrackets: true,
              mode: "text/" + code_type
            });
            code_content = $(_this).val();
            code_content = self.code_format(code_type, code_content);
            self.attrs.setAttribute(code_type, code_content);
            if (code_type === "js") {
              return self[code_type + "_editor"].on("change", function() {
                clearTimeout(self.timeout);
                return self.timeout = setTimeout(function() {
                  return self.ifr_refresh();
                }, 700);
              });
            } else {
              return self[code_type + "_editor"].on("change", function() {
                return self.ifr_refresh();
              });
            }
          };
        })(this));
      });
      querycheck = setInterval((function(_this) {
        return function() {
          if (_this.flag !== 0) {
            return;
          }
          _this.container.find(".mode-tab").eq(0).addClass("active");
          return clearInterval(querycheck);
        };
      })(this), 20);
    };

    Editor.prototype.code_format = function(type, content) {
      content = content.trim();
      switch (type) {
        case "html":
          content = beautify.html_beautify(content);
          break;
        case "css":
          content = beautify.css_beautify(content);
          break;
        case "js":
          content = beautify.js_beautify(content);
      }
      return content;
    };

    Editor.prototype.set_editor = function(type, val) {
      return this[type + "_editor"].getDoc().setValue(val);
    };

    Editor.prototype.set_layout = function() {
      this.container.find(".CodeMirror").removeClass("expansiondown expansionup");
      this.container.find("#mode-tabs").removeClass("tabup tabdown");
      switch (this.attrs.layout) {
        case 1:
          this.container.find("#mode-tabs").removeClass("tabup").addClass("tabdown");
          this.container.find(".remind").remove();
          this.container.find(".CodeMirror").removeClass("expansionup").addClass("expansiondown");
          this.container.find(".mode-tab").removeClass("active");
          this.container.find(".mode-tab").eq(0).addClass("active");
          break;
        case 2:
          this.container.find("#mode-tabs #file-dropdown-toggle #file-dropdown").hide();
          this.container.find(".CodeMirror").show().addClass("expansionup");
          this.container.find("#mode-tabs").addClass("tabup");
          this.container.find(".CodeMirror").eq(0).prepend("<div class='remind'>HTML</div>");
          this.container.find(".CodeMirror").eq(1).prepend("<div class='remind'>CSS</div>");
          this.container.find(".CodeMirror").eq(2).prepend("<div class='remind'>JS</div>");
          break;
        default:
          this.attrs.layout = 1;
          this.set_layout();
      }
    };

    Editor.prototype.event_bind = function() {
      var self;
      self = this;
      this.container.find("#mode-tabs").delegate("div", "click", function() {
        var toshow;
        if ($(this).hasClass("active")) {
          return;
        }
        self.container.find(".mode-tab").removeClass("active");
        $(this).addClass("active");
        self.container.find(".CodeMirror").removeClass("expansiondown");
        self.container.find(".CodeMirror").hide();
        toshow = $(this).attr("codetype");
        console.log(toshow);
        return self.container.find("#" + toshow).next().show();
      });
      this.container.find("#toggle-full-screen").click(function() {
        if ($(this).hasClass("full-screen-enabled")) {
          self.exit_fullscreen();
        } else {
          self.enter_fullscreen();
        }
        return $(this).toggleClass("full-screen-enabled");
      });
      this.container.find(".iframeread").click(function() {
        if (!$(this).hasClass("active")) {
          $(this).addClass("active");
          self.container.find(".codepanel").removeClass("narrow").addClass("expansionleft");
          return self.container.find(".renderpanel").removeClass("expansion").addClass("narrowleft");
        } else if (self.container.find(".coderead").hasClass("active")) {
          $(this).removeClass("active");
          self.container.find(".codepanel").removeClass("expansionleft narrowleft").addClass('narrow');
          return self.container.find(".renderpanel").removeClass("narrowleft expansionleft").addClass('expansion');
        } else {
          self.container.find(".coderead").click();
          return setTimeout(function() {
            return self.container.find(".iframeread").click();
          }, 500);
        }
      });
      this.container.find(".coderead").on("click", function() {
        if (!$(this).hasClass("active")) {
          $(this).addClass("active");
          self.container.find(".renderpanel").removeClass("narrow").addClass("expansionleft");
          return self.container.find(".codepanel").removeClass("expansion").addClass("narrowleft");
        } else if (self.container.find(".iframeread").hasClass("active")) {
          $(this).removeClass("active");
          self.container.find(".renderpanel").removeClass("expansionleft narrowleft").addClass("narrow");
          return self.container.find(".codepanel").removeClass("narrowleft expansionleft").addClass("expansion");
        } else {
          self.container.find(".iframeread").click();
          return setTimeout(function() {
            return self.container.find(".coderead").click();
          }, 500);
        }
      });
      return this.container.find(".mode").on("click", (function(_this) {
        return function() {
          return _this.attrs.layout++;
        };
      })(this));
    };

    Editor.prototype.enter_fullscreen = function() {
      var base, base1, base2, base3;
      if (typeof (base = this.container[0]).requestFullscreen === "function") {
        base.requestFullscreen();
      }
      if (typeof (base1 = this.container[0]).msRequestFullscreen === "function") {
        base1.msRequestFullscreen();
      }
      if (typeof (base2 = this.container[0]).mozRequestFullScreen === "function") {
        base2.mozRequestFullScreen();
      }
      if (typeof (base3 = this.container[0]).webkitRequestFullscreen === "function") {
        base3.webkitRequestFullscreen();
      }
    };

    Editor.prototype.exit_fullscreen = function() {
      if (typeof document.exitFullscreen === "function") {
        document.exitFullscreen();
      }
      if (typeof document.msExitFullscreen === "function") {
        document.msExitFullscreen();
      }
      if (typeof document.mozCancelFullScreen === "function") {
        document.mozCancelFullScreen();
      }
      if (typeof document.webkitExitFullscreen === "function") {
        document.webkitExitFullscreen();
      }
    };

    return Editor;

  })();
  return module.exports = Editor;
});
