// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Coder, Editor, Iframe, Layout;
  Iframe = require("../module/iframe");
  Coder = require("../module/coder");
  Layout = require("../module/layout");
  Editor = (function() {
    function Editor(container, attrs) {
      this.container = container;
      this.attrs = attrs;
      this.container = $(this.container);
      this.ifr = new Iframe(this.container, this);
      this.coder = new Coder(this.container, this, this.attrs);
      this.layout = new Layout(this.container, this.attrs);
    }

    Editor.prototype.set_editor = function(type, val) {
      return this[type + "_editor"].getDoc().setValue(val);
    };

    Editor.prototype.set_layout = function() {
      return this.layout.set_layout();
    };

    Editor.prototype.refresh = function() {
      return this.ifr.refresh();
    };

    return Editor;

  })();
  return module.exports = Editor;
});
