// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Editor, Element;
  require("jquery");
  Editor = require("./editor");
  Element = {};
  Element.init = function() {
    return Polymer("dingo-coder", {
      icon: "/img/logo.png",
      title: "Dingo Coder",
      layout: 1,
      ready: function() {
        return this.editor = new Editor(this.$.editor, this);
      },
      htmlChanged: function(oldVal, newVal) {
        return this.editor.set_editor("html", newVal);
      },
      cssChanged: function(oldVal, newVal) {
        return this.editor.set_editor("css", newVal);
      },
      jsChanged: function(oldVal, newVal) {
        return this.editor.set_editor("js", newVal);
      },
      velocityChanged: function(oldVal, newVal) {
        return this.editor.set_editor("velocity", newVal);
      },
      layoutChanged: function(oldVal, newVal) {
        return this.editor.set_layout();
      }
    });
  };
  return module.exports = Element;
});
