// Generated by CoffeeScript 1.9.2
(function() {
  return document.addEventListener("polymer-ready", function() {
    var editor;
    editor = document.querySelector("dingo-coder");
    editor.setAttribute("css", ".example {\n    margin-right: 0;\n    margin-left: 0;\n    background-color: #fff;\n    border-color: #ddd;\n    border-width: 1px;\n    border-radius: 4px 4px 0 0;\n    -webkit-box-shadow: none;\n    box-shadow: none;\n    position: relative;\n    padding: 45px 15px 45px 15px;\n    border-style: solid;\n}");
    return editor.setAttribute("html", "<link href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css\" rel=\"stylesheet\">\n<div class=\"example\">\n    <button type=\"button\" class=\"btn btn-default\">Default</button>\n    <button type=\"button\" class=\"btn btn-primary\">Primary</button>\n    <button type=\"button\" class=\"btn btn-success\">Success</button>\n    <button type=\"button\" class=\"btn btn-info\">Info</button>\n    <button type=\"button\" class=\"btn btn-warning\">Warning</button>\n    <button type=\"button\" class=\"btn btn-danger\">Danger</button>\n    <button type=\"button\" class=\"btn btn-link\">Link</button>\n</div>\n");
  });
})();
