// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Element, Index;
  Element = require("./element");
  Index = {};
  Index.init = function() {
    return Element.init();
  };
  return module.exports = Index;
});
