// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Element, Index, Service;
  Element = require("./element");
  Service = require("./service/service");
  Index = {};
  Index.init = function() {
    var service;
    service = new Service();
    return Element.init(service);
  };
  return module.exports = Index;
});
