// Generated by CoffeeScript 1.9.2
(function() {
  var bind, flag;
  bind = function(el, eve, fn, priority) {
    var _isIE;
    _isIE = window.addEventListener != null ? false : true;
    return el[_isIE ? "attachEvent" : "addEventListener"]("" + (_isIE ? "on" : "") + eve, fn, priority || false);
  };
  flag = false;
  return bind(window, "message", function(e) {
    if (flag) {
      return;
    }
    flag = true;
    window._dingo_element = JSON.parse(e.data);
    return console.log("From postMessage", window._dingo_element);
  });
})();

require.config({
  paths: {
    codemirror: "./vendor/codemirror",
    firebase: "./vendor/firebase/firebase"
  },
  shim: {
    firebase: {
      exports: "Firebase"
    }
  }
});
