// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var AuthService, Service, UserService;
  AuthService = require("./authService");
  UserService = require("./userService");
  Service = {};
  Service.authService = new AuthService();
  Service.userService = new UserService(Service);
  return module.exports = Service;
});
