// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var AuthService, Service;
  AuthService = require("./authService");
  Service = (function() {
    function Service() {
      this.authService = new AuthService(this.fbRef);
    }

    Service.prototype.getUserService = function() {
      return this.authService;
    };

    return Service;

  })();
  return module.exports = Service;
});
