// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Firebase, Service, UserService;
  Firebase = require("firebase");
  UserService = require("./userService");
  Service = (function() {
    function Service() {
      this.fbRef = new Firebase("https://dingo-coder.firebaseio.com/");
      this.userService = new UserService(this.fbRef);
    }

    Service.prototype.getUserService = function() {
      return this.userService;
    };

    return Service;

  })();
  return module.exports = Service;
});
