// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Layout;
  Layout = (function() {
    function Layout(container, attrs) {
      this.container = container;
      this.attrs = attrs;
    }

    Layout.prototype.set_layout = function() {
      this.container.find(".CodeMirror").removeClass("expansiondown expansionup");
      this.container.find("#mode-tabs").removeClass("tabup tabdown");
      switch (this.attrs.layout) {
        case 1:
          this.container.find("#mode-tabs").removeClass("tabup").addClass("tabdown");
          this.container.find(".remind").remove();
          this.container.find(".CodeMirror").removeClass("expansionup").addClass("expansiondown");
          this.container.find(".mode-tab").removeClass("active");
          this.container.find(".mode-tab").eq(0).addClass("active");
          break;
        case 2:
          this.container.find("#mode-tabs #file-dropdown-toggle #file-dropdown").hide();
          this.container.find(".CodeMirror").show().addClass("expansionup");
          this.container.find("#mode-tabs").addClass("tabup");
          this.container.find(".CodeMirror").eq(0).prepend("<div class='remind'>HTML</div>");
          this.container.find(".CodeMirror").eq(1).prepend("<div class='remind'>CSS</div>");
          this.container.find(".CodeMirror").eq(2).prepend("<div class='remind'>JS</div>");
          break;
        default:
          this.attrs.layout = 1;
          this.set_layout();
      }
    };

    Layout.prototype.enter_fullscreen = function() {
      var base, base1, base2, base3;
      if (typeof (base = this.container[0]).requestFullscreen === "function") {
        base.requestFullscreen();
      }
      if (typeof (base1 = this.container[0]).msRequestFullscreen === "function") {
        base1.msRequestFullscreen();
      }
      if (typeof (base2 = this.container[0]).mozRequestFullScreen === "function") {
        base2.mozRequestFullScreen();
      }
      if (typeof (base3 = this.container[0]).webkitRequestFullscreen === "function") {
        base3.webkitRequestFullscreen();
      }
    };

    Layout.prototype.exit_fullscreen = function() {
      if (typeof document.exitFullscreen === "function") {
        document.exitFullscreen();
      }
      if (typeof document.msExitFullscreen === "function") {
        document.msExitFullscreen();
      }
      if (typeof document.mozCancelFullScreen === "function") {
        document.mozCancelFullScreen();
      }
      if (typeof document.webkitExitFullscreen === "function") {
        document.webkitExitFullscreen();
      }
    };

    return Layout;

  })();
  return module.exports = Layout;
});
