// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Mode;
  Mode = {
    js: "javascript",
    javascript: "javascript",
    html: "htmlmixed",
    css: "css",
    velocity: "velocity"
  };
  return module.exports = Mode;
});
