// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Dingo, Editor, Mode, Service;
  Editor = require("./editor");
  Mode = require("./module/mode");
  Service = {};
  window.service = Service;
  Dingo = {};
  Dingo.init = function() {
    Polymer("dingo-coder", {
      icon: "/img/logo.png",
      title: "Dingo Coder",
      layout: 1,
      ready: function() {
        return this.editor = new Editor(this.$.editor, this, Service);
      },
      attributeChanged: function(attrName, oldVal, newVal) {
        if (Mode[attrName] != null) {
          this.editor.set_editor(attrName, newVal);
        }
        if (attrName === "js" || attrName === "css" || attrName === "html") {
          return this.editor.refresh();
        }
      }
    });
  };
  return module.exports = Dingo;
});
