// Generated by CoffeeScript 1.9.2
define(function(require, exports, module) {
  "use strict";
  var Coder, Editor, Iframe, Layout;
  Iframe = require("./module/iframe");
  Coder = require("./module/coder");
  Layout = require("./module/layout");
  Editor = (function() {
    function Editor(container, element, service) {
      this.container = container;
      this.element = element;
      this.service = service;
      this.container = $(this.container);
      this.ifr = new Iframe(this);
      this.coder = new Coder(this);
      this.layout = new Layout(this);
    }

    Editor.prototype.set_editor = function(type, val) {
      return this[type + "_editor"].getDoc().setValue(val);
    };

    Editor.prototype.set_layout = function() {
      return this.layout.set_layout();
    };

    Editor.prototype.refresh = function() {
      return this.ifr.refresh();
    };

    return Editor;

  })();
  return module.exports = Editor;
});
